apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    receivers:
    - name: 'notifications'
      email_configs:
      - to: aiswaryasarath847@gmail.com
        from: aiswaryasarath847@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: aiswaryasarath847@gmail.com
        auth_identity: aiswaryasarath847@gmail.com
        auth_password: test test test test
        send_resolved: true
        headers:
          subject: "Prometheus - Alert"
          text: "{{ range .Alerts }} Hi, \n{{ .Annotations.summary }}\n{{ .Annotations.description }} {{end}}"

      slack_configs:
      - channel: '#sre'
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'

    route:
      group_wait: 10s
      group_interval: 2m
      receiver: 'notifications'
      repeat_interval: 2m
